name: Python Linting

on:
  push:
    branches:
      - "!main"
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Python Linting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # apparently only ubuntu latest is available to run a contenairised job
        os: [ubuntu-latest]
        python-version: ["3.9"]
        architecture: ["x64"]

    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out code
        uses: actions/checkout@v3

      #----------------------------------------------
      #       set-up python
      #----------------------------------------------
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #       Formatting
      #----------------------------------------------
      - name: Format code with black
        run: |
          pip install black
          black tests scripts sdkit examples --line-length 120 --include="\.py"

      #----------------------------------------------
      #       Sorting imports
      #----------------------------------------------
      - name: Sorting imports with isort
        run: |
          pip install isort
          isort tests scripts sdkit examples --profile black

      #----------------------------------------------
      #       Removing unused imports and variables
      #----------------------------------------------
      - name: Remove unused imports with autoflake
        run: |
          pip install autoflake
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

      #----------------------------------------------
      #       Linting
      #----------------------------------------------
      - name: Linting code with flake8
        run: |
          pip install flake8
          flake8 tests scripts sdkit examples --max-line-length 120 --extend-ignore=E203,E402,E722 --per-file-ignores=__init__.py:F401

      #----------------------------------------------
      #       Committing all changes
      #----------------------------------------------
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Code formatted and linted"
          add: "."
          branch: ${{ github.ref }}
