name: Python Linting

on:
  push:
    branches:
      - "!main"
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Python Linting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # apparently only ubuntu latest is available to run a contenairised job
        os: [windows-latest]
        python-version: ["3.9"]
        architecture: ["x64"]

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #       Formatting and Linting
      #----------------------------------------------
      - name: Linting stage
        uses: weibullguy/python-lint-plus@v1.11.0
        with:
          python-root-list: "examples scripts sdkit tests"
          virtual-env: "python-lint-plus"
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.artchitecture }}
          use-docformatter: false
          use-pycodestyle: false
          use-black: true
          extra-black-options: "--line-length 120"
          use-isort: true
          extra-isort-options: "--profile black"
          use-flake8: true
          extra-flake8-options: "--max-line-length 120 --extend-ignore=E203,E402,E722 --per-file-ignores=__init__.py:F401"
